version: "3.4"

x-var: &SEQUENCER_PRIVATE_KEY
  SEQUENCER_PRIVATE_KEY=0xd2ab07f7c10ac88d5f86f1b4c1035d5195e81f27dbe62ad65e59cbf88205629b

x-var: &DEPLOYER_PRIVATE_KEY
  DEPLOYER_PRIVATE_KEY=0x754fde3f5e60ef2c7649061e06957c29017fe21032a8017132c0078e37f6193a

x-var: &RELAY_L1_WALLET_PRIV_KEY
  L1_WALLET_KEY=0xea8b000efb33c49d819e8d6452f681eed55cdf7de47d655887fc0e318906f2e7

x-var: &CUSTOM_RELAY_L1_WALLET_PRIV_KEY
  L1_WALLET_KEY=0x5b1c2653250e5c580dcb4e51c2944455e144c57ebd6a0645bd359d2e69ca0f0c

x-var: &L1_NODE_WEB3_URL
  L1_NODE_WEB3_URL=http://l1_chain:9545

x-var: &DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT
  DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT=http://l1_chain:9545

x-var: &L2_NODE_WEB3_URL
  L2_NODE_WEB3_URL=http://geth_l2:8545

x-var: &DEPLOYER_HTTP
  DEPLOYER_HTTP=http://deployer:8080

x-var: &DEPLOYER_URL
  DEPLOYER_URL=http://deployer:8080

x-var: &ADDRESS_MANAGER_ADDRESS
  ADDRESS_MANAGER_ADDRESS=0x3e4CFaa8730092552d9425575E49bB542e329981

services:
  data_transport_layer:
    environment:
      - *L1_NODE_WEB3_URL
      - *DEPLOYER_HTTP
      - *DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT
      - DATA_TRANSPORT_LAYER__SYNC_FROM_L1=true
      - DATA_TRANSPORT_LAYER__SYNC_FROM_L2=false
      - DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT=http://geth_l2:8545
      - DATA_TRANSPORT_LAYER__L2_CHAIN_ID=
      - DATA_TRANSPORT_LAYER__DB_PATH=/db
      - DATA_TRANSPORT_LAYER__SERVER_PORT=7878
      - DATA_TRANSPORT_LAYER__TRANSACTIONS_PER_POLLING_INTERVAL=1000
      - DATA_TRANSPORT_LAYER__CONFIRMATIONS=0
      - DATA_TRANSPORT_LAYER__POLLING_INTERVAL=500
      - DATA_TRANSPORT_LAYER__LOGS_PER_POLLING_INTERVAL=2000
      - DATA_TRANSPORT_LAYER__DANGEROUSLY_CATCH_ALL_ERRORS=true
      - DATA_TRANSPORT_LAYER__SERVER_HOSTNAME=0.0.0.0
      - DATA_TRANSPORT_LAYER__ADDRESS_MANAGER=
      - RETRIES=100

  geth_l2:
    environment:
      - *DEPLOYER_HTTP
      - *L1_NODE_WEB3_URL
      - ETH1_SYNC_SERVICE_ENABLE=true
      - ETH1_CTC_DEPLOYMENT_HEIGHT=8
      - ETH1_CONFIRMATION_DEPTH=0
      - ROLLUP_CLIENT_HTTP=http://data_transport_layer:7878
      - ROLLUP_POLL_INTERVAL_FLAG=3s
      - USING_OVM=true
      - CHAIN_ID=28
      - NETWORK_ID=28
      - DEV=true
      - DATADIR=/root/.ethereum
      - RPC_ENABLE=true
      - RPC_ADDR=geth_l2
      - RPC_CORS_DOMAIN=*
      - RPC_VHOSTS=*
      - RPC_PORT=8545
      - WS=true
      - WS_ADDR=0.0.0.0
      - IPC_DISABLE=true
      - TARGET_GAS_LIMIT=9000000
      - RPC_API=eth,net,rollup,web3
      - WS_API=eth,net,rollup,web3
      - WS_ORIGINS=*
      - GASPRICE=0
      - NO_USB=true
      - GCMODE=archive
      - NO_DISCOVER=true
      - ROLLUP_STATE_DUMP_PATH=http://deployer:8080/state-dump.latest.json
      - RETRIES=100

  batch_submitter:
    environment:
      - *SEQUENCER_PRIVATE_KEY
      - *L1_NODE_WEB3_URL
      - *L2_NODE_WEB3_URL
      - *DEPLOYER_HTTP
      - *ADDRESS_MANAGER_ADDRESS
      - DEBUG=info*,error*,warn*,debug*
      - MAX_L1_TX_SIZE=90000
      - MIN_L1_TX_SIZE=0
      - MAX_TX_BATCH_COUNT=50
      - MAX_STATE_BATCH_COUNT=50
      - POLL_INTERVAL=15000
      - NUM_CONFIRMATIONS=0
      - RESUBMISSION_TIMEOUT=15
      - FINALITY_CONFIRMATIONS=0
      - RUN_TX_BATCH_SUBMITTER=true
      - RUN_STATE_BATCH_SUBMITTER=true
      - MAX_BATCH_SUBMISSION_TIME=0
      - SAFE_MINIMUM_ETHER_BALANCE=0
      - CLEAR_PENDING_TXS=false
      - RETRIES=100

  l1_chain:
    environment:
      - ETH1_HTTP_PORT=9545
      - MNEMONIC=abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about

  deployer:
    environment:
      - *L1_NODE_WEB3_URL
      - *DEPLOYER_PRIVATE_KEY
      - *SEQUENCER_PRIVATE_KEY
      - HARDHAT=true
      - FRAUD_PROOF_WINDOW_SECONDS=0

  message_relayer:
    environment:
      - *L1_NODE_WEB3_URL
      - *L2_NODE_WEB3_URL
      - *DEPLOYER_HTTP
      - *RELAY_L1_WALLET_PRIV_KEY
      - *ADDRESS_MANAGER_ADDRESS
      - RETRIES=100
      - L1_BLOCK_OFFSET=0

  custom_message_relayer:
    environment:
      - *L1_NODE_WEB3_URL
      - *L2_NODE_WEB3_URL
      - *DEPLOYER_HTTP
      - *CUSTOM_RELAY_L1_WALLET_PRIV_KEY
      - *ADDRESS_MANAGER_ADDRESS
      - L1_TARGET=0x0
      - RETRIES=100
      - L1_BLOCK_OFFSET=0