global:
  tlsDisable: true # TODO: change to enable TLS

injector:
  enabled: false

server:
  ha:
    enabled: true
    replicas: 3

    raft:
      enabled: true
      setNodeId: true

      config: |
        ui = false
        log_level = "debug"
        cluster_name = "omgnetwork-cluster"

        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }

        seal "gcpckms" {
          region      = "global"
          project     = "omgnetwork-vault"
          key_ring    = "omgnetwork-vault-ring"
          crypto_key  = "omgnetwork-vault-unseal-key"
        }

        storage "raft" {
          path = "/vault/data"
        }

        service_registration "kubernetes" {}
  image:
    repository: vault # TODO: will change to the omgnetwork/vault image
    tag: "1.5.0" # TODO: will change to the appropriate tag for omgnetwork/vault
    pullPolicy: IfNotPresent

  extraEnvironmentVars:
    GOOGLE_REGION: global
    GOOGLE_PROJECT: omgnetwork-vault
    GOOGLE_APPLICATION_CREDENTIALS: /vault/userconfig/kms-creds/credentials.json

  extraVolumes:
    - type: secret
      name: "kms-creds"

  dev:
    enabled: false

  standalone:
    enabled: false

ui:
  enabled: false
