{{- if .Values.meshGateway.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "consul.fullname" . }}-mesh-gateway
  labels:
    app: {{ template "consul.name" . }}
    chart: {{ template "consul.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: mesh-gateway
{{- if or .Values.global.bootstrapACLs .Values.global.enablePodSecurityPolicies }}
rules:
{{- if .Values.global.enablePodSecurityPolicies }}
  - apiGroups: ["policy"]
    resources: ["podsecuritypolicies"]
    resourceNames:
      - {{ template "consul.fullname" . }}-mesh-gateway
    verbs:
      - use
{{- end }}
{{- if .Values.global.bootstrapACLs }}
  - apiGroups: [""]
    resources:
      - secrets
    resourceNames:
      - {{ template "consul.fullname" . }}-mesh-gateway-acl-token
    verbs:
      - get
{{- end }}
{{- else }}
rules: []
{{- end }}
{{- end }}
