apiVersion: 1

deleteDatasources:
- name: 'Prometheus'

datasources:
- access: 'proxy'
  editable: true
  is_default: true
  name: 'Prometheus'
  uid: 'ddshms3dlineoe'
  org_id: 1
  type: 'prometheus'
  url: 'http://prometheus:9090'
  version: 1