[profile.default]
src = 'src'
out = 'forge-artifacts'
script = 'scripts'
optimizer = true
optimizer_runs = 999999

remappings = [
  '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts',
  '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts',
  '@rari-capital/solmate/=lib/solmate',
  "@cwia/=lib/clones-with-immutable-args/src",
  'forge-std/=lib/forge-std/src',
  'ds-test/=lib/ds-test/src'
]
extra_output = ['devdoc', 'userdoc', 'metadata', 'storageLayout']
bytecode_hash = 'none'
build_info = true
build_info_path = 'artifacts/build-info'
ffi = true
fuzz_runs = 16

fs_permissions = [
  { 'access'='read-write', 'path'='./.resource-metering.csv' },
  { 'access'='read-write', 'path'='./deployments/' },
  { 'access'='read', 'path'='./deploy-config/' },
  { 'access'='read', 'path'='./broadcast/' },
  { access = 'read', path = './forge-artifacts/' },
  { 'access'='write', 'path'='./semver-lock.json' },
]

[profile.ci]
fuzz_runs = 512
