[default]
src = 'contracts'
 # We need to build seperate artifacts for forge and hh, because they each expect a different
 # structure for the artifacts directory.
out = 'forge-artifacts'
optimizer = true
optimizer_runs = 999999
remappings = [
  '@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/',
  '@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/',
  '@eth-optimism/contracts/=node_modules/@eth-optimism/contracts/',
  'excessively-safe-call/=node_modules/excessively-safe-call/src/',
  'solmate/=node_modules/@rari-capital/solmate/src',
  'forge-std/=node_modules/forge-std/src',
  'ds-test/=node_modules/ds-test/src'
]
bytecode_hash = "none"
