apiVersion: v2
name: vault
version: 0.6.0
appVersion: 1.4.2
description: Official HashiCorp Vault Chart
home: https://www.vaultproject.io
icon: https://github.com/hashicorp/vault/raw/f22d202cde2018f9455dec755118a9b84586e082/Vault_PrimaryLogo_Black.png
keywords: ["vault", "security", "encryption", "secrets", "management", "automation", "infrastructure"]
sources:
  - https://github.com/hashicorp/vault
  - https://github.com/hashicorp/vault-helm
  - https://github.com/hashicorp/vault-k8s
