# Log level.
# Possible values: trace | debug | info | warn | error | crit
# Default: debug
log_level = "debug"

[signer_service]
# URL to the signer service
url = "http://localhost:1234"
tls_ca_cert = "tls/ca.crt"
tls_cert = "tls/tls.crt"
tls_key = "tls/tls.key"

[healthz]
# Whether or not to enable healthz endpoint
enabled = true
# Host for the healthz endpoint to listen on
host = "0.0.0.0"
# Port for the above.
port = 8080

[metrics]
# Whether or not to enable Prometheus metrics
enabled = true
# Host for the Prometheus metrics endpoint to listen on.
host = "0.0.0.0"
# Port for the above.
port = 9761

[wallets.default]
# OP Stack Chain ID
# see https://community.optimism.io/docs/useful-tools/networks/
chain_id = 420
# Signer method to use
# Possible values: signer | static
signer_method = "signer"
# Address used to send transactions
address="0x0123"
# For static signer method, the private key to use
# private_key=""
# Transaction value in wei
tx_value=100000000000000
# Gas limit
gas_limit=21000
# Gas tip cap
gas_tip_cap=2000000000
# Fee cap
gas_fee_cap=20000000000

[providers.p1]
# URL to the RPC provider
url = "http://localhost:8551"
# Read only providers are only used to check for transactions
read_only = true
# Interval to poll the provider for expected transactions
read_interval = "1s"
# Interval to submit new transactions to the provider
send_interval = "5s"
# Wallet to be used for sending transactions
wallet = "default"

[providers.p2]
# Uncomment to disable this provider
# disabled=true
# URL to the RPC provider
url = "http://localhost:8552"
# Read only providers are only used to check for transactions
read_only = false
# Interval to poll the provider for expected transactions
read_interval = "2s"
# Interval to submit new transactions to the provider
send_interval = "3s"
# Wallet to be used for sending transactions
wallet = "default"
