version: "3.4"

x-var: &SEQUENCER_PRIVATE_KEY
  SEQUENCER_PRIVATE_KEY=0xd2ab07f7c10ac88d5f86f1b4c1035d5195e81f27dbe62ad65e59cbf88205629b

x-var: &DEPLOYER_PRIVATE_KEY
  DEPLOYER_PRIVATE_KEY=0x754fde3f5e60ef2c7649061e06957c29017fe21032a8017132c0078e37f6193a

#x-var: &RELAY_L1_WALLET_PRIV_KEY
#  L1_WALLET_KEY=0xea8b000efb33c49d819e8d6452f681eed55cdf7de47d655887fc0e318906f2e7

#anything will do, as long as it has ETH in it, I think
x-var: &FRAUD_PROVER_WALLET_PRIV_KEY
#  FP_WALLET_KEY=0x5b1c2653250e5c580dcb4e51c2944455e144c57ebd6a0645bd359d2e69ca0f0c # Not sure where this key came from. Re-enable if desired
  FP_WALLET_KEY=0xc526ee95bf44d8fc405a158bb884d9d1238d99f0612e9f33d006bb0789009aaa  # Hardhat default account #14

#this is the address that will trigger the batch_submitter to inject fake state roots
x-var: &FRAUD_SUBMISSION_ADDRESS
  FRAUD_SUBMISSION_ADDRESS=0xb0dd88dfcc929a78fec13daa1bd77843e267c729
  
x-var: &L1_NODE_WEB3_URL
  L1_NODE_WEB3_URL=http://l1_chain:9545

x-var: &L2_NODE_WEB3_URL
  L2_NODE_WEB3_URL=http://geth_l2:8545

x-var: &VERIFIER_URL
  L2_NODE_WEB3_URL=http://verifier:8045

x-var: &ROLLUP_CLIENT_HTTP
  ROLLUP_CLIENT_HTTP=http://data_transport_layer:7878

x-var: &ROLLUP_STATE_DUMP_PATH
  ROLLUP_STATE_DUMP_PATH=http://deployer:8080/state-dump.latest.json

x-var: &DEPLOYER_HTTP
  DEPLOYER_HTTP=http://deployer:8080

x-var: &DEPLOYER_URL
  DEPLOYER_URL=http://deployer:8080

x-var: &DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT
  DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT=http://l1_chain:9545

x-var: &DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT
  DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT=http://geth_l2:8545

x-var: &ADDRESS_MANAGER_ADDRESS
  ADDRESS_MANAGER_ADDRESS=0x3e4CFaa8730092552d9425575E49bB542e329981

services:

  data_transport_layer:
    environment:
      - *L1_NODE_WEB3_URL
      - *DEPLOYER_HTTP
      - *DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT
      - *DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT
      - DATA_TRANSPORT_LAYER__SYNC_FROM_L1=true
      - DATA_TRANSPORT_LAYER__SYNC_FROM_L2=false
      - DATA_TRANSPORT_LAYER__L2_CHAIN_ID=28
      - DATA_TRANSPORT_LAYER__DB_PATH=/db
      - DATA_TRANSPORT_LAYER__SERVER_PORT=7878
      - DATA_TRANSPORT_LAYER__TRANSACTIONS_PER_POLLING_INTERVAL=1000
      - DATA_TRANSPORT_LAYER__CONFIRMATIONS=0
      - DATA_TRANSPORT_LAYER__POLLING_INTERVAL=500
      - DATA_TRANSPORT_LAYER__LOGS_PER_POLLING_INTERVAL=2000
      - DATA_TRANSPORT_LAYER__DANGEROUSLY_CATCH_ALL_ERRORS=true
      - DATA_TRANSPORT_LAYER__SERVER_HOSTNAME=0.0.0.0
      - DATA_TRANSPORT_LAYER__ADDRESS_MANAGER=
      - RETRIES=100

  geth_l2:
    environment:
      - *DEPLOYER_HTTP
      - *L1_NODE_WEB3_URL
      - *ROLLUP_STATE_DUMP_PATH
      - *ROLLUP_CLIENT_HTTP
      - ETH1_SYNC_SERVICE_ENABLE=true
      - ETH1_CTC_DEPLOYMENT_HEIGHT=8
      - ETH1_CONFIRMATION_DEPTH=0
      - ROLLUP_POLL_INTERVAL_FLAG=3s
      - USING_OVM=true
      - CHAIN_ID=28
      - NETWORK_ID=28
      - DEV=true
      - DATADIR=/root/.ethereum
      - RPC_ENABLE=true
      - RPC_ADDR=geth_l2
      - RPC_CORS_DOMAIN=*
      - RPC_VHOSTS=*
      - RPC_PORT=8545
      - WS=true
      - WS_ADDR=0.0.0.0
      - IPC_DISABLE=true
      - TARGET_GAS_LIMIT=9000000
      - RPC_API=eth,net,rollup,web3
      - WS_API=eth,net,rollup,web3
      - WS_ORIGINS=*
      - GASPRICE=0
      - NO_USB=true
      - GCMODE=archive
      - NO_DISCOVER=true
      - RETRIES=100

  batch_submitter:
    environment:
      - *SEQUENCER_PRIVATE_KEY
      - *L1_NODE_WEB3_URL
      - *L2_NODE_WEB3_URL
      - *DEPLOYER_HTTP
      - *ADDRESS_MANAGER_ADDRESS
      - *FRAUD_SUBMISSION_ADDRESS
      - DEBUG=info*,error*,warn*,debug*
      - MAX_L1_TX_SIZE=90000
      - MIN_L1_TX_SIZE=0
      - MAX_TX_BATCH_COUNT=50
      - MAX_STATE_BATCH_COUNT=50
      - POLL_INTERVAL=15000
      - NUM_CONFIRMATIONS=0
      - RESUBMISSION_TIMEOUT=15
      - FINALITY_CONFIRMATIONS=0
      - RUN_TX_BATCH_SUBMITTER=true
      - RUN_STATE_BATCH_SUBMITTER=true
      - MAX_BATCH_SUBMISSION_TIME=0
      - SAFE_MINIMUM_ETHER_BALANCE=0
      - CLEAR_PENDING_TXS=false
      - RETRIES=100

  l1_chain:
    environment:
      - ETH1_HTTP_PORT=9545
      - MNEMONIC=abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about

  deployer:
    environment:
      - *L1_NODE_WEB3_URL
      - *DEPLOYER_PRIVATE_KEY
      - *SEQUENCER_PRIVATE_KEY
      - HARDHAT=true
      - FRAUD_PROOF_WINDOW_SECONDS=0

  message_relayer:
    environment:
      - *L1_NODE_WEB3_URL
      - *L2_NODE_WEB3_URL
      - *DEPLOYER_HTTP
      - *RELAY_L1_WALLET_PRIV_KEY
      - *ADDRESS_MANAGER_ADDRESS
      - RETRIES=100

  verifier:
    environment:
      - ROLLUP_VERIFIER_ENABLE=true
      - *DEPLOYER_HTTP
      - *L1_NODE_WEB3_URL
      - *ROLLUP_CLIENT_HTTP
      - *ROLLUP_STATE_DUMP_PATH
      - ETH1_SYNC_SERVICE_ENABLE=true
      - ETH1_CTC_DEPLOYMENT_HEIGHT=8
      - ETH1_CONFIRMATION_DEPTH=0
      - ROLLUP_POLL_INTERVAL_FLAG=3s
      - USING_OVM=true
      - CHAIN_ID=28
      - NETWORK_ID=28
      - DEV=true
      - DATADIR=/root/.ethereum
      - RPC_ENABLE=true
      - RPC_ADDR=verifier
      - RPC_CORS_DOMAIN=*
      - RPC_VHOSTS=*
      - RPC_PORT=8045
      - WS=true
      - WS_ADDR=0.0.0.0
      - IPC_DISABLE=true
      - TARGET_GAS_LIMIT=9000000
      - RPC_API=eth,net,rollup,web3
      - WS_API=eth,net,rollup,web3
      - WS_ORIGINS=*
      - GASPRICE=0
      - NO_USB=true
      - GCMODE=archive
      - NO_DISCOVER=true
      - RETRIES=60


  fraud_prover:
    environment:
      - *L1_NODE_WEB3_URL
      - *FRAUD_PROVER_WALLET_PRIV_KEY
      - *ADDRESS_MANAGER_ADDRESS
#     - *VERIFIER_URL
      - L2_NODE_WEB3_URL=http://verifier:8045
      - NO_TIMEOUT=true
      - POLLING_INTERVAL=5000
      - RUN_GAS_LIMIT=8999999
      - RELAY_GAS_LIMIT=8999999
#     - FROM_L2_TRANSACTION_INDEX=0
      - L1_BLOCK_OFFSET=0
      - L2_BLOCK_OFFSET=1
      - L1_START_OFFSET=8
      - RETRIES=60
