name: integration

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - '*rc'
      - 'regenesis/*'
  pull_request:
  workflow_dispatch:

jobs:
  integration:
    runs-on: ubuntu-latest
    env:
        DOCKER_BUILDKIT: 1
        COMPOSE_DOCKER_CLI_BUILD: 1
    steps:
      # Monorepo tests
      - uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Build the services
        working-directory: ./ops
        run: ./scripts/build-ci.sh

      - name: Bring the stack up
        working-directory: ./ops
        run: docker-compose up -d

      - name: Run the integration tests
        working-directory: ./ops
        run: docker-compose run integration_tests

      # Examples Tests
      - name: Test & deploy hardhat-example on Ethereum (regression)
        working-directory: ./examples/hardhat
        run: |
          yarn deploy
          yarn test:integration

      - name: Test & deploy hardhat-example on Optimistic Ethereum
        working-directory: ./examples/hardhat
        run: |
          yarn deploy:ovm
          yarn test:integration:ovm

      - name: Test & deploy waffle-example on Ethereum (regression)
        working-directory: ./examples/waffle
        run: |
          yarn compile
          yarn test:integration

      - name: Test & deploy waffle-example on Optimistic Ethereum
        working-directory: ./examples/waffle
        run: |
          yarn compile:ovm
          yarn test:integration:ovm

      - name: Test & deploy truffle-example on Ethereum (regression)
        working-directory: ./examples/truffle
        run: |
          yarn compile
          yarn test:integration
          yarn deploy

      - name: Test & deploy truffle-example on Optimistic Ethereum
        working-directory: ./examples/truffle
        run: |
          yarn compile:ovm
          yarn test:integration:ovm
      
      - name: Test & deploy l1-l2-deposit-withdrawal example on Ethereum with cross-domain message passing
        working-directory: ./examples/l1-l2-deposit-withdrawal
        run: |
          yarn compile
          yarn test
      
      - name: Test l1-l2-deposit-withdrawal example on Optimistic Ethereum with cross-domain message passing
        working-directory: ./examples/l1-l2-deposit-withdrawal
        run: |
          yarn compile:ovm
          yarn test:integration:ovm
