name: Setup & Run Integration Test Suite

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Setup & Run Integration Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: webfactory/ssh-agent@v0.4.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_READ }}

      - name: Setup node
        uses: actions/setup-node@v1

      - name: Build
        run: |
          git clone https://github.com/ethereum-optimism/optimism-integration.git \
              $HOME/optimism-integration \
              --recurse-submodules
          REPO=$(echo $GITHUB_REPOSITORY | cut -d '/' -f2)
          cd $HOME/optimism-integration/$REPO
          REMOTE="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git"
          git remote add gh $REMOTE
          git fetch gh $GITHUB_SHA
          git checkout $GITHUB_SHA
          cd $HOME/optimism-integration
          ./docker/build.sh

      - name: Test
        run: |
          cd $HOME/optimism-integration
          ./test.sh
