name: Build and publish forkdiff github-pages
permissions:
  contents: write
on:
  push:
    branches:
      - celo[0-9]+
jobs:
  deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1000  # make sure to fetch the old commit we diff against

      - name: Build forkdiff
        uses: "docker://protolambda/forkdiff:0.1.0"
        with:
          args: -repo=/github/workspace -fork=/github/workspace/fork.yaml -out=/github/workspace/index.html

      - name: Build pages
        run: |
          mkdir -p tmp/pages
          mv index.html tmp/pages/index.html
          touch tmp/pages/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: tmp/pages
          clean: true
