name: Contracts lint, test and static analysis

on:
  push:
    branches:
      - 'main'
      - 'staging'
  pull_request:
  workflow_dispatch:

env:
  PYTEST_ADDOPTS: "--color=yes"

defaults:
    run:
      shell: bash
      working-directory: ./packages/contracts

jobs:
  yarn-test:
    runs-on: ubuntu-latest
    name: Yarn Test
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-node@v2
        with:
            node-version: '14'
            cache: 'yarn'
      - run: yarn install

      - name: Build with HH
        run: yarn build:hh

      - name: Test
        run: yarn test:hh

      - name: Lint
        run: yarn lint:check

  forge-test:
    runs-on: ubuntu-latest
    name: Forge Test
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Build with Forge
        run: yarn build:forge

      - name: Test with Forge
        run: yarn test:forge

  slither:
    runs-on: ubuntu-latest
    name: Slither
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-node@v2
        with:
            node-version: '14'
            cache: 'yarn'
      - run: yarn install

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Slither
        run: pip3 install slither-analyzer

      - name: Run Slither
        run: yarn slither
        continue-on-error: true
