name: Test MIPS EVM

on: [push, pull_request]

jobs:
  unit:
    name: MIPS EVM matches unicorn
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install Go + Node
      run: |
        sudo apt-get update
        sudo apt-get -y --no-install-recommends install golang-1.16 nodejs npm
    - name: Install unicorn
      run: |
        ./build_unicorn.sh
    - name: Install yarn
      run: |
        npm install --global yarn
        yarn install
    - name: Hardhat Compile
      run: npx hardhat compile
    - name: Build minigeth and run default block (cache)
      run: |
        ./run.sh
        minigeth/go-ethereum 13284491
    - name: Install Python deps
      run: pip3 install -r mipigo/requirements.txt
    - name: Build minigeth for embedded
      run: |
        cd mipigo
        ./build.sh
    - name: All MIPS EVM tests
      run: cd mipsevm && go test
