
on: [push, pull_request]
name: Cannon Test
jobs:
  cannon-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: unicorn commit hash
        run: |
          git rev-parse HEAD > /tmp/unicorn-commit-hash.txt
      - name: cached libunicorn
        uses: actions/cache@v3
        with:
          path: |
            ./unicorn/build
          key:
            unicorn-build-{{ hashFiles('/tmp/unicorn-commit-hash.txt') }}
          restore-keys: |
            unicorn-build-{{ hashFiles('/tmp/unicorn-commit-hash.txt') }}
      - name: install libunicorn
        working-directory: .
        run: make libunicorn
      - uses: actions/cache@v3
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          # * Build cache (Mac)
          # * Build cache (Windows)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            ~\AppData\Local\go-build
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-
      - name: Build examples
        working-directory: ./example
        run: make bin/minimal.elf
      - name: build contracts
        working-directory: ./contracts
        run: forge build
      - name: mipsevm tests
        working-directory: ./mipsevm
        run: go test ./...
