name: Test Challenge

on: pull_request

jobs:
  unit:
    name: Challenge on block 13284469
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install Toolchain
      run: |
        sudo apt-get update
        sudo apt-get -y --no-install-recommends install golang-1.17 nodejs make cmake pkg-config
        npm install --global pnpm
    - name: Build
      run: make libunicorn minigeth_mips minigeth_prefetch mipsevm nodejs
    - name: Run test challenge
      run: make test_challenge
