name: typescript / contracts

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - '*rc'
      - 'regenesis/*'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        # only install dependencies if there was a change in the deps
        # if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test
        env:
          FORCE_COLOR: 1
          ENABLE_GAS_REPORT: 1
      - name: Print gas report
        run: cat packages/contracts/gas-report.txt

      - name: Run codechecks
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        working-directory: ./packages/contracts
        run: yarn codechecks
        env:
          CC_SECRET: ${{ secrets.CC_SECRET }}

  # A hack that allows running a job only if a specific directory changed.
  # Ref: https://github.community/t/run-job-only-if-folder-changed/118292
  is-contracts-package:
    name: Check files for changes to the contracts package
    # This job will break on a push event, so we just skip it,
    # which in turn skips the test-coverage job.
    if: ${{ github.event_name != 'push' }}
    outputs:
      run_coverage: ${{ steps.check_files.outputs.run_coverage }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: git fetch origin $GITHUB_BASE_REF

      - name: check modified files
        id: check_files
        run: |
          echo "=============== list modified files ==============="
          git diff --name-only origin/$GITHUB_BASE_REF HEAD -- .

          echo "========== check paths of modified files =========="
          git diff --name-only origin/$GITHUB_BASE_REF HEAD -- . > files.txt
          while IFS= read -r file
          do
            echo $file
            if [[ $file != packages/contracts/* ]]; then
              echo "This modified files are not in the contracts package."
              echo "::set-output name=run_coverage::false"
              break
            else
              echo "::set-output name=run_coverage::true"
            fi
          done < files.txt

  test-coverage:
    name: Generate test coverage
    needs: is-contracts-package
    if: needs.is-contracts-package.outputs.run_coverage == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        # only install dependencies if there was a change in the deps
        # if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Build
        run: yarn build

      - name: Test Coverage
        run: yarn test:coverage
        # Tests are quite brittle when instrumented by Solidity Coverage.
        # If tests pass in the Test job above, tests failing during coverage shouldn't break CI.
        continue-on-error: true
      - uses: codecov/codecov-action@v1
        with:
          files: ./packages/contracts/coverage.json
          fail_ci_if_error: false
          verbose: true
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch history
        run: git fetch
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        # only install dependencies if there was a change in the deps
        # if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Lint JS and TS
        run: yarn lint:check

      - name: Lint Solidity
        working-directory: ./packages/contracts
        run: yarn lint:contracts
