name: typescript / contracts

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - '*rc'
      - 'release/*'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        # only install dependencies if there was a change in the deps
        # if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Check yarn.lock for changes
        run: git diff --exit-code

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test
        env:
          FORCE_COLOR: 1
          ENABLE_GAS_REPORT: 1
      - name: Print gas report
        run: cat packages/contracts/gas-report.txt

      - name: Run codechecks
        working-directory: ./packages/contracts
        run: yarn codechecks
        env:
          CC_SECRET: ${{ secrets.CC_SECRET }}

  test-coverage:
    name: Generate test coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        # only install dependencies if there was a change in the deps
        # if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Build
        run: yarn build

      - name: Test Coverage
        run: yarn test:coverage

      - uses: codecov/codecov-action@v1
        with:
          files: ./packages/contracts/coverage.json
          fail_ci_if_error: true
          verbose: true
          flags: contracts
      - uses: codecov/codecov-action@v1
        with:
          files: ./packages/core-utils/coverage.json
          fail_ci_if_error: false
          verbose: true
          flags: core-utils
      - uses: codecov/codecov-action@v1
        with:
          files: ./packages/data-transport-layer/coverage.json
          fail_ci_if_error: false
          verbose: true
          flags: data-transport-layer
      - uses: codecov/codecov-action@v1
        with:
          files: ./packages/message-relayer/coverage.json
          fail_ci_if_error: false
          verbose: true
          flags: message-relayer
      - uses: codecov/codecov-action@v1
        with:
          files: ./packages/sdk/coverage.json
          fail_ci_if_error: false
          verbose: true
          flags: sdk

  depcheck:
    name: Check for unused dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        # only install dependencies if there was a change in the deps
        # if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Check packages/contracts
        working-directory: ./packages/contracts
        run: npx depcheck

      - name: Check packages/core-utils
        working-directory: ./packages/core-utils
        run: npx depcheck

      - name: Check packages/data-transport-layer
        working-directory: ./packages/data-transport-layer
        run: npx depcheck

      - name: Check packages/message-relayer
        working-directory: ./packages/message-relayer
        run: npx depcheck

      - name: Check packages/sdk
        working-directory: ./packages/sdk
        run: npx depcheck

      - name: Check integration-tests
        working-directory: ./integration-tests
        run: npx depcheck

  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch history
        run: git fetch
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        # only install dependencies if there was a change in the deps
        # if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Lint
        run: yarn lint:check
