name: Build & Tag Container, Push UAT build to ECR

on:
  push:
    branches:
      - uat

jobs:
  build:
    name: Build, Tag & push UAT build to ECR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_CI_USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_CI_USER_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Tag rollback image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: optimism/rollup-microservices
          IMAGE_TAG: uat
        run: |
          MANIFEST=$(aws ecr batch-get-image --repository-name $ECR_REGISTRY/$ECR_REPOSITORY --image-ids imageTag=$IMAGE_TAG --query 'images[].imageManifest' --output text)
          ROLLBACK_TAG="${IMAGE_TAG}_ROLLBACK_$(date +%Y-%m-%d_%H:%M:%S)"
          aws ecr put-image --repository-name $ECR_REGISTRY/$ECR_REPOSITORY --image-tag $ROLLBACK_TAG --image-manifest "$MANIFEST"

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: optimism/rollup-microservices
          IMAGE_TAG: uat
        run: |
          docker build -f Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Logout of Amazon ECR
        if: always()
        run: docker logout ${{ steps.login-ecr.outputs.registry }}
